### ISSUE TITLE
[NEW] - Notifications for failed SHIELD backups

### ISSUE THREAD

**Issue by michaelmccaskill** [shieldproject/shield#683] opened 2020-04-28 19:20 UTC
We would like SHIELD to have the capability of notifying us of failed backups.

**Is your feature request related to a problem? Please describe.**
Due to concourse kit deployments, the path to postgresql changed. This caused the `pg_dump` to fail. We were unaware that this could happen.

**Describe the solution you'd like**
- Email with a link to the failing job
- Slack notification to a specific channel with details

**Describe alternatives you've considered**
- Dynatrace integration
- Splunk integration

**Comment by jhunt** [comment] 2020-06-26 11:01
This is a duplicate of #407

**Closed** 2020-06-26 11:01 UTC
Labels: duplicate

**Comment by michaelmccaskill** [comment] 2020-06-26 11:37
Does this mean #407 is going to be worked on in the near future?

**Comment by jhunt** [comment] 2020-06-26 11:47
#407 is one of those tickets that I had always hoped someone would PR.  However, given the current _involvement_ of the SHIELD community in this project, I wouldn't expect that any time soon.

In v9, currently slated for September 2020, we are greatly reducing the scope of this project and exposing more of the internals for external integrations (i.e. monitoring systems like Prometheus / Alert Manager) to pick up some of the stuff like this.
