### ISSUE TITLE
[BUG] Creating a Backup Job in the Web UI Stays on the Create Backup Job page after completion

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#553] opened 2019-06-07 15:25 UTC
**Describe the bug**
After configuring the backup job using the wizard, clicking the Create Backup Job button causes the button to grey out until the request comes back - but when the request comes back 200, the page does not change, giving the impression that creating the backup job was unsuccessful.

**To Reproduce**
1. Use the wizard to create a backup job
2. Click on Create Backup Job
3. Wait.

**Expected behavior**
The page should change - presumably to either the list of data systems, or the page of the data system that  was created.

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.2.1

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: Windows
 - Browser: Firefox
 - Version: 67.0.1

**Additional context**

**Comment by thomasmitchell** [comment] 2019-06-07 15:26
Even worse - this made me click the create backup job button multiple times, creating multiple instances of the same job.

**Comment by thomasmitchell** [comment] 2019-06-07 15:27
Even worse, I can't delete data systems from the Web UI

**Comment by jhunt** [comment] 2019-08-22 15:44
I was unable to reproduce this on latest (8.4.x-ish) master, either with a new data system or a preexisting data system.

**Comment by thomasmitchell** [comment] 2019-08-23 19:16
This is caused by the websocket being closed before target creation.

**Comment by thomasmitchell** [comment] 2019-09-11 15:18
Caused by #612

**Comment by jhunt** [comment] 2019-09-13 17:18
If that's the case, i'm going to close it.

**Closed by jhunt** 2019-09-13 17:18 UTC
Labels: triage
